import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import styled from 'styled-components';

const LinkStyle = styled.a`
  background-color: #fafafa;
  border-radius: 5px;
  border: 2px solid transparent;
  padding: 10px 15px;
  margin: 0 10px;
  cursor: pointer;
  &:hover {
    border: 2px solid #ccc;
  }
`

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Frontend Tester
        </h1>

        <p className={styles.description}>
          Go to the quiz page to get started
        </p>

        <div className={styles.grid}>
          <Link href="/quizzes">
            <LinkStyle>Quiz Page</LinkStyle>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
